FROM	postgres:15.3	

# copying the sql files to the docker container
#WORKDIR /var/lib/postgresql/
#RUN chown -Rh postgres:postgres /var/lib/postgresql/data
#RUN usermod -u 999 -o postgres
#RUN groupmod -g 999 postgres

#USER postgres

#COPY	services/postgresql/dumpfile .
#COPY services/postgresql/init-db.sh /docker-entrypoint-initdb.d/init-db.sh
